💚 Attempt to  fix pipeline build for sharp package
See https://sharp.pixelplumbing.com/install/#cross-platform

The build in the GitHub Actions pipeline was failing with this error (ref https://github.com/jondarrer/promptrecovery.co.uk/actions/runs/14872086114/job/41762385673):

Failed to compile.

./assets/images/image1.jpg
Error: Could not load the "sharp" module using the linux-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/home/runner/work/promptrecovery.co.uk/promptrecovery.co.uk/node_modules/sharp/lib/sharp.js:121:9)
    at Module._compile (node:internal/modules/cjs/loader:1730:14)
    at Object..js (node:internal/modules/cjs/loader:1895:10)
    at Module.load (node:internal/modules/cjs/loader:1465:32)
    at Function._load (node:internal/modules/cjs/loader:1282:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.<anonymous> (node:internal/modules/cjs/loader:1487:12)
    at mod.require (/home/runner/work/promptrecovery.co.uk/promptrecovery.co.uk/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:135:16)